### ISSUE TITLE
It's not true that Taskwarrior has no scopes

### ISSUE THREAD

**Issue by Minoru** [ForNeVeR/praefectus#1]
In the README section [“Why not Taskwarrior?”](https://github.com/ForNeVeR/praefectus/blob/e9580910c4d1d97fd5375cbdd266dbcb4fe39300/Readme.md#why-not-taskwarrior), point 9 says:
> Taskwarrior has no "scopes" (e.g. for home and office work).

This isn't true: Taskwarrior has [contexts](https://taskwarrior.org/docs/context.html), which are essentially filters that are applied automatically and that you can switch between.

**Comment by ForNeVeR** [comment]
Thanks for note!
